### PR TITLE
Debug CI

### PR DESCRIPTION
**Pull request by madig**

### CODE REVIEW

**Comment by anthrotype** [comment]
@madig since you're touching the CI setup, why don't we also build arm64 and universal2 wheels for the latest Mac chips? See how uharfbuzz did that

**Comment by m4rc1e** [comment]
> why don't we also build arm64 and universal2 wheels for the latest Mac chips? See how uharfbuzz did that

oooh! is this something we could use for ft, ttfa etc as well? (apologies for the hijack)

**Comment by anthrotype** [comment]
@m4rc1e the trick to build arm64 wheels is to use cibuildwheel and macOS 11. Simon already did it for ttfautohint-py https://github.com/fonttools/ttfautohint-py/pull/8

**Comment by m4rc1e** [comment]
Sweet thank you Cosimo!

**Comment by madig** [comment]
I think the `auto64` marker builds all 64 bit things for ARM: https://cibuildwheel.readthedocs.io/en/stable/options/#archs.

**Comment by anthrotype** [comment]
I only see the x86_64 wheels been built at https://github.com/googlefonts/cu2qu/pull/194/checks?check_run_id=3281444036#step:5:1748

**Comment by anthrotype** [comment]
Khaled explicitly listed all three of them in https://github.com/harfbuzz/uharfbuzz/blob/732390ac8ba59d6e2e2e9dc7521f865e6c3a72b5/pyproject.toml#L20-L21 and his setup worked. Maybe GH runners do not actually run on the M1 chip and they only cross-compile

**Pull request merged**
